"""Add pgvector and ICP tables

Revision ID: 45fcf6643f76
Revises: bc889f05a3c8
Create Date: 2026-04-22 21:21:21.683033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


revision = '45fcf6643f76'
down_revision = 'bc889f05a3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.alter_column('icp_personas', 'vector_embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('icp_personas', 'vector_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    # ### end Alembic commands ###
