"""Added ICP persona and ICPRules for users

Revision ID: bc889f05a3c8
Revises: 0001
Create Date: 2026-04-21 20:28:36.365044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bc889f05a3c8'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vector_embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icp_personas_id'), 'icp_personas', ['id'], unique=False)
    op.create_table('user_icp_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('criteria_field', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('target_value', sa.String(), nullable=False),
    sa.Column('point_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_icp_rules_id'), 'user_icp_rules', ['id'], unique=False)
    op.add_column('users', sa.Column('latest_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'latest_login_at')
    op.drop_index(op.f('ix_user_icp_rules_id'), table_name='user_icp_rules')
    op.drop_table('user_icp_rules')
    op.drop_index(op.f('ix_icp_personas_id'), table_name='icp_personas')
    op.drop_table('icp_personas')
    # ### end Alembic commands ###
